//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerationWinForm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowTop {
            get {
                return ((int)(this["WindowTop"]));
            }
            set {
                this["WindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowLeft {
            get {
                return ((int)(this["WindowLeft"]));
            }
            set {
                this["WindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MostRecentTabUsed {
            get {
                return ((int)(this["MostRecentTabUsed"]));
            }
            set {
                this["MostRecentTabUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAutoCheckTypes {
            get {
                return ((bool)(this["checkBoxAutoCheckTypes"]));
            }
            set {
                this["checkBoxAutoCheckTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxCustomRange {
            get {
                return ((bool)(this["checkBoxCustomRange"]));
            }
            set {
                this["checkBoxCustomRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string textBoxCustomFrom {
            get {
                return ((string)(this["textBoxCustomFrom"]));
            }
            set {
                this["textBoxCustomFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string textBoxCustomTo {
            get {
                return ((string)(this["textBoxCustomTo"]));
            }
            set {
                this["textBoxCustomTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[TestMethod]")]
        public string textBoxCustoAttribute {
            get {
                return ((string)(this["textBoxCustoAttribute"]));
            }
            set {
                this["textBoxCustoAttribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("public")]
        public string textBoxCustPublic {
            get {
                return ((string)(this["textBoxCustPublic"]));
            }
            set {
                this["textBoxCustPublic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("void")]
        public string textBoxCustoVoid {
            get {
                return ((string)(this["textBoxCustoVoid"]));
            }
            set {
                this["textBoxCustoVoid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestMethod_")]
        public string textBoxCustoTestMethod {
            get {
                return ((string)(this["textBoxCustoTestMethod"]));
            }
            set {
                this["textBoxCustoTestMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Method_Name_Returned_True_or_False_on_Condition")]
        public string textBoxCustoMethodName {
            get {
                return ((string)(this["textBoxCustoMethodName"]));
            }
            set {
                this["textBoxCustoMethodName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("const")]
        public string textBoxCustoExpectedCosntant {
            get {
                return ((string)(this["textBoxCustoExpectedCosntant"]));
            }
            set {
                this["textBoxCustoExpectedCosntant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int comboBoxCustoExpectedType {
            get {
                return ((int)(this["comboBoxCustoExpectedType"]));
            }
            set {
                this["comboBoxCustoExpectedType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("expected")]
        public string textBoxCustoExpectedWord {
            get {
                return ((string)(this["textBoxCustoExpectedWord"]));
            }
            set {
                this["textBoxCustoExpectedWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("=")]
        public string textBoxCustoExpectedEqualSign {
            get {
                return ((string)(this["textBoxCustoExpectedEqualSign"]));
            }
            set {
                this["textBoxCustoExpectedEqualSign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string textBoxCustoExpectedValue {
            get {
                return ((string)(this["textBoxCustoExpectedValue"]));
            }
            set {
                this["textBoxCustoExpectedValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("const")]
        public string textBoxCustoConstantSource {
            get {
                return ((string)(this["textBoxCustoConstantSource"]));
            }
            set {
                this["textBoxCustoConstantSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int comboBoxCustoSourceType {
            get {
                return ((int)(this["comboBoxCustoSourceType"]));
            }
            set {
                this["comboBoxCustoSourceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("source")]
        public string textBoxCustoSourceWord {
            get {
                return ((string)(this["textBoxCustoSourceWord"]));
            }
            set {
                this["textBoxCustoSourceWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("=")]
        public string textBoxCustoSourceEqualSign {
            get {
                return ((string)(this["textBoxCustoSourceEqualSign"]));
            }
            set {
                this["textBoxCustoSourceEqualSign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"laval\"")]
        public string textBoxCustoSourceValue {
            get {
                return ((string)(this["textBoxCustoSourceValue"]));
            }
            set {
                this["textBoxCustoSourceValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int comboBoxCustoResultReturnedType {
            get {
                return ((int)(this["comboBoxCustoResultReturnedType"]));
            }
            set {
                this["comboBoxCustoResultReturnedType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("result")]
        public string textBoxCustoResultWord {
            get {
                return ((string)(this["textBoxCustoResultWord"]));
            }
            set {
                this["textBoxCustoResultWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("=")]
        public string textBoxCustoResultEqualSign {
            get {
                return ((string)(this["textBoxCustoResultEqualSign"]));
            }
            set {
                this["textBoxCustoResultEqualSign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".IsPalindrome")]
        public string textBoxcustoResultFunctionName {
            get {
                return ((string)(this["textBoxcustoResultFunctionName"]));
            }
            set {
                this["textBoxcustoResultFunctionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(source);")]
        public string textBoxCustoResultSourceWord {
            get {
                return ((string)(this["textBoxCustoResultSourceWord"]));
            }
            set {
                this["textBoxCustoResultSourceWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Assert.")]
        public string textBoxCustoAssertWord {
            get {
                return ((string)(this["textBoxCustoAssertWord"]));
            }
            set {
                this["textBoxCustoAssertWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int comboBoxCustoAssertMethod {
            get {
                return ((int)(this["comboBoxCustoAssertMethod"]));
            }
            set {
                this["comboBoxCustoAssertMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(")]
        public string textBoxCustoAssertOpenParenthesis {
            get {
                return ((string)(this["textBoxCustoAssertOpenParenthesis"]));
            }
            set {
                this["textBoxCustoAssertOpenParenthesis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("result")]
        public string textBoxCustoAssertResultWord {
            get {
                return ((string)(this["textBoxCustoAssertResultWord"]));
            }
            set {
                this["textBoxCustoAssertResultWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string textBoxCustoAssertComma {
            get {
                return ((string)(this["textBoxCustoAssertComma"]));
            }
            set {
                this["textBoxCustoAssertComma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("expected")]
        public string textBoxCustoAssertExpectedWord {
            get {
                return ((string)(this["textBoxCustoAssertExpectedWord"]));
            }
            set {
                this["textBoxCustoAssertExpectedWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(");")]
        public string textBoxCustoAssertClosingParenthesis {
            get {
                return ((string)(this["textBoxCustoAssertClosingParenthesis"]));
            }
            set {
                this["textBoxCustoAssertClosingParenthesis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Translations.xml")]
        public string LanguageFileName {
            get {
                return ((string)(this["LanguageFileName"]));
            }
            set {
                this["LanguageFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public string LastLanguageUsed {
            get {
                return ((string)(this["LastLanguageUsed"]));
            }
            set {
                this["LastLanguageUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxCustoResultFunctionClass {
            get {
                return ((string)(this["textBoxCustoResultFunctionClass"]));
            }
            set {
                this["textBoxCustoResultFunctionClass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int WindowHeight {
            get {
                return ((int)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int WindowWidth {
            get {
                return ((int)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string textBoxCodeLineRangeFrom {
            get {
                return ((string)(this["textBoxCodeLineRangeFrom"]));
            }
            set {
                this["textBoxCodeLineRangeFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public string textBoxCodeLineRangeTo {
            get {
                return ((string)(this["textBoxCodeLineRangeTo"]));
            }
            set {
                this["textBoxCodeLineRangeTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxCodeLineSentence1 {
            get {
                return ((string)(this["textBoxCodeLineSentence1"]));
            }
            set {
                this["textBoxCodeLineSentence1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxCodeLineSentence2 {
            get {
                return ((string)(this["textBoxCodeLineSentence2"]));
            }
            set {
                this["textBoxCodeLineSentence2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxCodeLineSentence3 {
            get {
                return ((string)(this["textBoxCodeLineSentence3"]));
            }
            set {
                this["textBoxCodeLineSentence3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxCodeLineSentence4 {
            get {
                return ((string)(this["textBoxCodeLineSentence4"]));
            }
            set {
                this["textBoxCodeLineSentence4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxCodeLineSentence5 {
            get {
                return ((string)(this["textBoxCodeLineSentence5"]));
            }
            set {
                this["textBoxCodeLineSentence5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool radioButtonCodeLineOneLine {
            get {
                return ((bool)(this["radioButtonCodeLineOneLine"]));
            }
            set {
                this["radioButtonCodeLineOneLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool radioButtonCodeLineIncrementNumber {
            get {
                return ((bool)(this["radioButtonCodeLineIncrementNumber"]));
            }
            set {
                this["radioButtonCodeLineIncrementNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%")]
        public string textBoxCodeLineIteratorChar {
            get {
                return ((string)(this["textBoxCodeLineIteratorChar"]));
            }
            set {
                this["textBoxCodeLineIteratorChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxCodeLineResultAssembled {
            get {
                return ((bool)(this["checkBoxCodeLineResultAssembled"]));
            }
            set {
                this["checkBoxCodeLineResultAssembled"] = value;
            }
        }
    }
}
